task 6 done
v1lezz/yadro-project pull request #13
Opened 2024-05-15 03:08 UTC by v1lezz

@kirreal
@maxan98
@vbelogrudov

2024-05-15 10:09 UTC, vbelogrudov requested changes
Привет!

есть проблемы со стартом:
```

➜  v1lezz/yadro-project git:(main) ✗ ./xkcd-server -c config.yaml 
panic: duplicated key 'port' in struct config.PostgresDBConfig [recovered]
	panic: duplicated key 'port' in struct config.PostgresDBConfig

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc000053c60)
	/home/vbelogrudov/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:294 +0x6d
panic({0x8f6780?, 0xc000116200?})
	/home/vbelogrudov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/panic.go:770 +0x132
gopkg.in/yaml%2ev3.(*decoder).mappingStruct(0xc000126000, 0xc00013a1e0, {0x97e400?, 0xc000118080?, 0x40d0bf?})
	/home/vbelogrudov/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:881 +0x10fb
gopkg.in/yaml%2ev3.(*decoder).mapping(0xc000126000, 0xc00013a1e0, {0x97e400?, 0xc000118080?, 0xc0001161a0?})
	/home/vbelogrudov/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:786 +0xa5
gopkg.in/yaml%2ev3.(*decoder).unmarshal(0xc000126000, 0xc00013a1e0, {0x97e400?, 0xc000118080?, 0xc0000536a0?})
	/home/vbelogrudov/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:510 +0x3ea
gopkg.in/yaml%2ev3.(*decoder).mappingStruct(0xc000126000, 0xc00013a0a0, {0x96daa0?, 0xc000118080?, 0x40d0bf?})
	/home/vbelogrudov/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:935 +0xfab
gopkg.in/yaml%2ev3.(*decoder).mapping(0xc000126000, 0xc00013a0a0, {0x96daa0?, 0xc000118080?, 0x0?})
	/home/vbelogrudov/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:786 +0xa5
gopkg.in/yaml%2ev3.(*decoder).unmarshal(0xc000126000, 0xc00013a0a0, {0x96daa0?, 0xc000118080?, 0x8655c5?})
	/home/vbelogrudov/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:510 +0x3ea
gopkg.in/yaml%2ev3.(*decoder).document(...)
	/home/vbelogrudov/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:527
gopkg.in/yaml%2ev3.(*decoder).unmarshal(0xc000126000, 0xc00013a000, {0x96daa0?, 0xc000118080?, 0x600?})
	/home/vbelogrudov/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:498 +0x28a
gopkg.in/yaml%2ev3.(*Decoder).Decode(0xc000053ce0, {0x8f6660, 0xc000118080})
	/home/vbelogrudov/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:131 +0x1d6
yadro-project/internal/config.NewConfig({0x7ffdc02b4108?, 0xe13050?})
	/home/vbelogrudov/projects/course/v1lezz/yadro-project/internal/config/config.go:55 +0x1e5
main.main()
	/home/vbelogrudov/projects/course/v1lezz/yadro-project/cmd/xkcd/main.go:31 +0x1aa

```

2024-05-15 10:09 UTC, vbelogrudov commented on internal/adapters/repository/pg_repository.go
> +		g.Go(func() error {
не стоит использовать транзакцию из нескольких горутин. Даже если это позволятеся, БД будет выполнять операции последовательно.

2024-05-15 10:14 UTC, vbelogrudov requested changes
также не удалось пока запустить через docker-compose up:

```
➜  v1lezz/yadro-project git:(main) ✗ docker-compose up  
Creating network "yadro-project_xkcd_net" with driver "bridge"
Creating yadro-project_db_1 ... done
Creating yadro-project_server_1 ... error

ERROR: for yadro-project_server_1  Cannot start service server: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./xkcd-server -c=config.yaml": stat ./xkcd-server -c=config.yaml: no such file or directory: unknown

ERROR: for server  Cannot start service server: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./xkcd-server -c=config.yaml": stat ./xkcd-server -c=config.yaml: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.

```

2024-05-20 06:40 UTC, vbelogrudov reviewed
Привет!

по коду почти нет замечаний, все еще не запускается docker compose. Запустил руками с правками. Очень желательно какие-то логи, например,
log.Println("Run full update")
log.Println("Update index")....

2024-05-20 06:40 UTC, vbelogrudov commented on Dockerfile
> +FROM golang:latest
лучше воспользоваться multistage build - https://docs.docker.com/build/building/multi-stage/

2024-05-20 06:40 UTC, vbelogrudov commented on internal/adapters/index/index_pg.go
> +	rows.Close()
лучше через defer,  сразу после проверки err на 45 строчке

2024-05-20 06:42 UTC, vbelogrudov commented on internal/adapters/index/index_pg.go
> +		if errors.Is(err, sql.ErrNoRows) {
смешивание pgx pool errors с пакетом sql. Чтобы заработало, нужно поменять везде на  pgx.ErrNoRows

2024-05-20 06:47 UTC, vbelogrudov requested changes
лучше отладить все без docker / docker-compose.

2024-05-20 06:58 UTC, vbelogrudov commented
Последнее, до чего я доотлаживал:

➜  v1lezz/yadro-project git:(main) ✗ curl -X POST localhost:9000/update
error: error update comics: error add comics in storage: is not exist%

2024-05-20 06:59 UTC, vbelogrudov requested changes

2024-05-20 06:59 UTC, vbelogrudov commented on internal/adapters/repository/pg_repository.go
> +	if !isExist {
какая здесь логика? Если не найдет, просто не добавляем? Вроде должно быть наоборот

2024-05-20 08:16 UTC, vbelogrudov reviewed
➜  v1lezz/yadro-project git:(main) ✗ curl -X POST localhost:9000/update
{"new":0,"total":2933}
➜  v1lezz/yadro-project git:(main) ✗ curl -X POST localhost:9000/update
error: error update comics: error get count comics in storage: error get count comics: closed pool%                                               ➜  v1lezz/yadro-project git:(main) ✗ curl -X POST localhost:9000/update
error: error update comics: error get count comics in storage: error get count comics: closed pool%                                               ➜  v1lezz/yadro-project git:(main) ✗ curl -X POST localhost:9000/update
error: error update comics: error get count comics in storage: error get count comics: closed pool%              

последующие апдейты приходят с ошибками

2024-05-20 08:16 UTC, vbelogrudov commented on internal/adapters/repository/pg_repository.go
> +		g.Go(func() error {
так не работает, лучше без горутин внутри транзакции:

➜  v1lezz/yadro-project git:(main) ✗ curl -X POST localhost:9000/update
error: error update comics: error add comics in storage: error add keyword: conn busy%

2024-05-20 08:16 UTC, vbelogrudov commented on internal/adapters/index/index_pg.go
> +	g, gCtx := errgroup.WithContext(ctx)
лучше без горутин внутри транзакции:

➜  v1lezz/yadro-project git:(main) ✗ curl -X POST localhost:9000/update            
error: error update comics: error update index: error update index: conn busy%

2024-05-20 08:16 UTC, vbelogrudov commented on internal/adapters/repository/migrations/20240514095531_create_comics_index.sql
> +    keyword VARCHAR(255) NOT NULL
keyword VARCHAR(255) NOT NULL UNIQUE

иначе инсерт не сработает:

➜  v1lezz/yadro-project git:(main) ✗ curl -X POST localhost:9000/update
error: error update comics: error add comics in storage: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification (SQLSTATE 42P10)%

2024-05-28 14:11 UTC, v1lezz commented on internal/adapters/repository/pg_repository.go
> +		g.Go(func() error {
fixed

2024-05-28 14:31 UTC, v1lezz commented on internal/adapters/index/index_pg.go
> +		if errors.Is(err, sql.ErrNoRows) {
fixed

2024-05-28 14:31 UTC, v1lezz commented
> лучше отладить все без docker / docker-compose.

fixed

2024-05-28 14:31 UTC, v1lezz commented on internal/adapters/repository/pg_repository.go
> +	if !isExist {
fixed

2024-05-28 14:31 UTC, v1lezz commented on internal/adapters/index/index_pg.go
> +	g, gCtx := errgroup.WithContext(ctx)
fixed

2024-05-28 14:33 UTC, v1lezz commented on internal/adapters/repository/migrations/20240514095531_create_comics_index.sql
> +    keyword VARCHAR(255) NOT NULL
fixed

2024-05-29 07:30 UTC, vbelogrudov reviewed
привет!
как бы я не запускал, у меня всегда останавливается  /update на свежеустановденном постгресе:

```
➜  v1lezz/yadro-project git:(main) ✗ curl -X POST localhost:9000/update
error: error update comics: error update index: error update index: ERROR: insert or update on table "index" violates foreign key constraint "index_comics_id_fkey" (SQLSTATE 23503)% 
```             

postgres log:
```

2024-05-29 07:26:01.856 UTC [75] STATEMENT:  SELECT version_id, is_applied from goose_db_version ORDER BY id DESC
2024-05-29 07:27:43.504 UTC [81] ERROR:  insert or update on table "index" violates foreign key constraint "index_comics_id_fkey"
2024-05-29 07:27:43.504 UTC [81] DETAIL:  Key (comics_id)=(42) is not present in table "keyword".
2024-05-29 07:27:43.504 UTC [81] STATEMENT:  INSERT INTO index(keyword_id, comics_id) VALUES ((SELECT id FROM keyword WHERE keyword = $1), $2)
2024-05-29 07:28:01.062 UTC [60] LOG:  checkpoint starting: time
```

2024-05-29 07:43 UTC, vbelogrudov commented
последующие /update проходят, но ничего не ищется:
```

➜  v1lezz/yadro-project git:(main) ✗ curl 'localhost:9000/pics?search=apple'       
error: error get comics from server: error search comics: error search from repository: error get comics from repository: error get query of comics: closed pool%             
```

2024-05-29 07:44 UTC, vbelogrudov approved these changes
по коду замечаний нет, а со схемой ДБ надо разбираться

2024-05-29 08:36 UTC, v1lezz commented
> по коду замечаний нет, а со схемой ДБ надо разбираться

хорошо, в следующем пр внесу изменения, протестирую сам, чтоб все работало как надо)

2024-05-29 08:36 UTC, merged

2024-05-29 09:44 UTC, vbelogrudov commented on internal/adapters/repository/migrations/20240514095531_create_comics_index.sql
> +    comics_id INTEGER NOT NULL REFERENCES keyword(id) ON UPDATE RESTRICT ON DELETE CASCADE,
comics_id references comics(id)

2024-05-29 09:50 UTC, v1lezz commented on internal/adapters/repository/migrations/20240514095531_create_comics_index.sql
> +    comics_id INTEGER NOT NULL REFERENCES keyword(id) ON UPDATE RESTRICT ON DELETE CASCADE,
действительно))) невнимателен)
в следующем пр будет исправлено)